version: '3.8'

services:
  # React App
  client:
    build:
      context: ./React-js-Master-Detail-CRUD-with-Asp.Net-Web-API/restaurant-app
      dockerfile: Dockerfile
    restart: always
    networks:
      - mynetwork
    ports:
      - "3000:80"
    depends_on:
      - api

  # ASP.NET Core API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    networks:
      - mynetwork
    ports:
      - "5000:5000"
    
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DBServer: "db"
      ConnectionStrings__DefaultConnection: "Data Source=db;Database=RestaurantDB;user id=sa;password=Password789;Trusted_Connection=false;"

  # MySQL Database

  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: db         # tên container
    restart: always
    hostname: mssql
    networks:
      - mynetwork
    environment:
      SA_PASSWORD: Password789          #Thiết lập password
      ACCEPT_EULA: Y
      # Express:

    volumes:
      - vmssql:/var/opt/mssql # thư mục lưu DB
      - ./bk:/var/opt/mssql/backup      # thư  mục chứa file backup
    ports:
      - "1433:1433"                     # cổng kết nối
volumes:
  vmssql:
    external: true
networks:
  mynetwork: