version: '3.8'

services:
  # React App
  client:
    build:
      context: ./React-js-Master-Detail-CRUD-with-Asp.Net-Web-API/restaurant
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # networks:
    #   - mynetwork
    depends_on:
      - api

  
  # ASP.NET Core API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    # networks:
    #   - mynetwork

  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    restart: always
    environment:
      SA_PASSWORD: Password789          #Thiết lập password
      ACCEPT_EULA: Y
      # Express:
    volumes:
      - ./data/data:/var/opt/mssql/data
      - ./data/log:/var/opt/mssql/log # thư mục lưu DB
      - ./bk:/var/opt/mssql/backup      # thư  mục chứa file backup
    ports:
      - "1433:1433"                     # cổng kết nối
    # networks:
    #   - mynetwork
# networks:
#   mynetwork:
#     driver: bridge
# volumes:
#     vmssql:
#       external: true
