version: "3.7"

services:
  runner:
    image: myoung34/github-runner:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RUNNER_SCOPE: repo
      RUNNER_NAME_PREFIX: myrunner
      LABELS: some-label
      REPO_URL: https://github.com/NguyenVanHung24/Restaurant
      EPHEMERAL: 1
      ACCESS_TOKEN: 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
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
