version: "3.7"

services:
  runner:
    image: myoung34/github-runner:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RUNNER_SCOPE: repo
      RUNNER_NAME_PREFIX: myrunner
      LABELS: some-label
      REPO_URL: https://github.com/NguyenVanHung24/Restaurant
      EPHEMERAL: 1
      ACCESS_TOKEN: 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
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.4'
          memory: 512M
