name: BuildFE

on:
  push:
    branches:
      - fe
      - main
  pull_request:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: hungnv9999/app


jobs:

  
  
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, some-label]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIKEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.SSH_USER }} >> ~/.ssh/known_hosts
      - name: copy builds to server
        run: |
          rsync -vrm  .output/* ${{ secrets.SSH_USER }}:/var/www/example.com/
          ssh ${{ secrets.SSH_HOST }} "ls"

