# name: Deploy

# on:
#   push:
#     branches:
#       - fe
#       - be
#       - main
#   # pull_request:
#   #   branches:
#   #     - main

# env:
#   # Use docker.io for Docker Hub if empty
#   REGISTRY: docker.io
#   # github.repository as <account>/<repo>
#   IMAGE_NAME: hungnv9999/app
#   runs-on: [self-hosted, some-label]

# jobs:

  

  
  
