name: Deploy

on:
  push:
    branches:
      - fe
      - be
      - main
  # pull_request:
  #   branches:
  #     - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: hungnv9999/app


jobs:

  
  
  run-docker-compose:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: SSH deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SHH_KEY }}
        script: |
          cd restaurant
          ./deploy.sh

