# name: Docker Image Publish

# on:
#   push:
#     branches: [ "" ]
#     # Publish semver tags as releases.
#     tags: [ 'v*.*.*' ]

# env:
#   # Use docker.io for Docker Hub if empty
#   # github.repository as <account>/<repo>
#   IMAGE_NAME: ${{ github.repository }}


# jobs:
#   build:
#     runs-on: ubuntu-latest


#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.USERNAME}}
#           password: ${{ secrets.PASSWORD}}

#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           tags: akoskm/my-image:latest
#           push: ${{ github.event_name != 'pull_request' }} # Don't push on PR
#           labels: ${{ steps.meta.outputs.labels }}
#           cache-from: type=gha
#           cache-to: type=gha,mode=max