name: BuildBe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: [self-hosted, some-label]
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
           dotnet-version: 7
      - run: dotnet restore
      - name: Build App
        run: dotnet build
  build_image:
    runs-on: [self-hosted, some-label]
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t my-appapi .
